### ISSUE TITLE
Investigate the memory leak check implemented in ESBMC

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1259]
The memory leak check implemented in ESBMC was disabled in the last competition due to many incorrect results.

This recent PR reports some numbers: https://github.com/esbmc/esbmc/pull/1250. However, there are still more issues beyond the `getenv` function that needs to be investigated.

**Comment by fbrausse** [comment]
Looking at `c/weaver/unroll-2.wvr.yml`, ESBMC claims "forgotten memory" (which is true, an array is malloc'ed and not free'd), but to me it seems that they assume `abort()` would not perform memleak checks since they encode assumptions via `assume_abort_if_not()`, which aborts. When modifying it:
```diff
diff --git a/c/weaver/unroll-2.wvr.c b/c/weaver/unroll-2.wvr.c
index 1d1d1f580c..87c94190b2 100644
--- a/c/weaver/unroll-2.wvr.c
+++ b/c/weaver/unroll-2.wvr.c
@@ -77,13 +77,13 @@ int main() {
   f = create_fresh_int_array(size);
   
   assume_abort_if_not(n < 4294967296 / 2);
-
+#if 0 /* let's ignore the finite state manipulation done here */
   // main method
   pthread_create(&t1, 0, thread1, 0);
   pthread_create(&t2, 0, thread2, 0);
   pthread_join(t1, 0);
   pthread_join(t2, 0);
-
+#endif
   assume_abort_if_not(x1 != x2);
   reach_error();
 
@@ -95,8 +95,10 @@ int *create_fresh_int_array(int size) {
   assume_abort_if_not(size <= (((size_t) 4294967295) / sizeof(int)));
 
   int* arr = (int*)malloc(sizeof(int) * (size_t)size);
+#if 0 /* this is what ESBMC does anyway, only takes time */
   for (int i = 0; i < size; i++) {
     arr[i] = __VERIFIER_nondet_int();
   }
+#endif
   return arr;
 }
```
ESBMC still claims `forgotten memory` because abort() calls the __ESBMC_memory_leak_checks(). Removing that from the abort() OM makes the modified one work as SV-COMP intends (VERIFICATION SUCCESSFUL).

However, like so many things in SV-COMP, this is highly underspecified (unless I missed something). For memsafety they claim they look at all finite executions. To me calling `abort()` does terminate (abnormally) the execution, making it definitely finite...

**Comment by fbrausse** [comment]
Looks like something with the threads. Consider the version where `abort()` doesn't do the __ESBMC_memory_leak_checks() and
```diff
diff --git a/c/weaver/unroll-2.wvr.c b/c/weaver/unroll-2.wvr.c
index 1d1d1f580c..f8998a1126 100644
--- a/c/weaver/unroll-2.wvr.c
+++ b/c/weaver/unroll-2.wvr.c
@@ -78,12 +78,16 @@ int main() {
   
   assume_abort_if_not(n < 4294967296 / 2);
 
+  n = 0;
+#if 1 /* change to 0 for VERIFICATION SUCCESSFUL */
   // main method
   pthread_create(&t1, 0, thread1, 0);
-  pthread_create(&t2, 0, thread2, 0);
+  // pthread_create(&t2, 0, thread2, 0);
   pthread_join(t1, 0);
-  pthread_join(t2, 0);
-
+  // pthread_join(t2, 0);
+#else
+  thread1(0);
+#endif
   assume_abort_if_not(x1 != x2);
   reach_error();
 
@@ -95,8 +99,10 @@ int *create_fresh_int_array(int size) {
   assume_abort_if_not(size <= (((size_t) 4294967295) / sizeof(int)));
 
   int* arr = (int*)malloc(sizeof(int) * (size_t)size);
+#if 0
   for (int i = 0; i < size; i++) {
     arr[i] = __VERIFIER_nondet_int();
   }
+#endif
   return arr;
 }
```
As the comment says, when `thread1()` is run in a different thread, ESBMC finds a "forgotten memory", if it's run in the main thread it does not. I'm not too familiar with how the threads are handled internally, but my gut says: the exec-guard isn't taken into account for the memleak-checks, because the `x1 != x2` condition should always be false and the assert should never be reached.

**Comment by lucasccordeiro** [comment]
@fbrausse: This is a very interesting observation.

Let me try to play with a simple example.

Is there a memory leak in this multi-threaded C program?

````C
#include <stdlib.h>
#include <pthread.h>

int *shared;

void* t1(void *arg){
  shared = (int *) malloc(sizeof(int));
  return NULL;
}

void* t2(void *arg){
  free(shared);
  return NULL;
}

int main() {
  pthread_t id1, id2;
  pthread_create(&id1, NULL, t1, NULL);
  pthread_create(&id2, NULL, t2, NULL);
  return 0;
}
````

Valgrind and ESBMC point out that there is a memory leak.

**Comment by lucasccordeiro** [comment]
Valgrind and ESBMC still point out the memory leak here:

````C
#include <stdlib.h>
#include <pthread.h>

int *shared;

void* t1(void *arg){
  shared = (int *) malloc(sizeof(int));
  return NULL;
}

void* t2(void *arg){
  free(shared);
  return NULL;
}

int main() {
  pthread_t id1, id2;
  pthread_create(&id1, NULL, t1, NULL);
  pthread_create(&id2, NULL, t2, NULL);

  pthread_join(id1, NULL);
  pthread_join(id2, NULL);
  return 0;
}
````

**Comment by lucasccordeiro** [comment]
ESBMC and Valgrind report that there is no memory leak here:

````C
#include <stdlib.h>
#include <pthread.h>

int *shared;

void* t1(void *arg){
  shared = (int *) malloc(sizeof(int));
  free(shared);
  return NULL;
}

void* t2(void *arg){
  return NULL;
}

int main() {
  pthread_t id1, id2;
  pthread_create(&id1, NULL, t1, NULL);
  pthread_create(&id2, NULL, t2, NULL);

  pthread_join(id1, NULL);
  pthread_join(id2, NULL);
  return 0;
}
````

**Comment by lucasccordeiro** [comment]
@fbrausse and I discussed this issue today.

Here is the smallest example that exposes the bug in ESBMC:

$esbmc main.c --memory-leak-check


````C
#include <stdlib.h>
#include <pthread.h>

int *shared;

void *t1(void *arg)
{
  return NULL;
}
int main()
{
  shared = (int *)malloc(sizeof(int));
  pthread_t id1;
  pthread_create(&id1, NULL, t1, NULL);
  pthread_join(id1, NULL);
  free(shared);
  return 0;
}
````

**Comment by fbrausse** [comment]
More recent numbers in https://github.com/esbmc/esbmc/pull/1270#issuecomment-1674267484 item (b). This is the list of new-incorrect ones when the wrapper gives the false_memtrack output instead of unknown:
- [ ] c/array-examples/relax-2-2.yml
- [ ] c/termination-recursive-malloc/chunk1-2.yml
- [ ] c/memsafety-bftpd/bftpd_2a.yml
- [ ] c/loop-industry-pattern/aiob_4.c.v+cfa-reducer.yml
- [ ] c/loop-industry-pattern/aiob_4.c.v+lh-reducer.yml
- [ ] c/loop-industry-pattern/aiob_4.c.v+lhb-reducer.yml
- [ ] c/loop-industry-pattern/aiob_4.c.v+nlh-reducer.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_calloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_calloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_malloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_malloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_realloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_realloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_calloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_calloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_malloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_malloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_realloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_realloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_calloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_calloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_malloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_malloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_realloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_realloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_calloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_calloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_malloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_malloc_68_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_realloc_45_bad.yml
- [ ] c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_realloc_68_bad.yml
- [ ] c/pthread/twostage_3.yml
- [ ] c/pthread-driver-races/char_generic_nvram_nvram_unlocked_ioctl_write_nvram.yml
- [ ] c/pthread-driver-races/char_generic_nvram_read_nvram_nvram_unlocked_ioctl.yml
- [ ] c/pthread-driver-races/char_generic_nvram_read_nvram_write_nvram.yml
- [ ] c/pthread-divine/tls_destructor_worker.yml
- [ ] c/goblint-regression/06-symbeq_15-list_entry_nr.yml
- [ ] c/goblint-regression/09-regions_02-list_nr.yml
- [ ] c/goblint-regression/09-regions_04-list2_nr.yml
- [ ] c/goblint-regression/09-regions_06-ptra_nr.yml
- [ ] c/goblint-regression/09-regions_09-arraylist.yml
- [ ] c/goblint-regression/09-regions_11-arraylist_nr.yml
- [ ] c/goblint-regression/09-regions_12-arraycollapse_rc.yml
- [ ] c/goblint-regression/09-regions_13-arraycollapse_nr.yml
- [ ] c/goblint-regression/09-regions_17-arrayloop_nr.yml

**Comment by lucasccordeiro** [comment]
I think ESBMC reports the correct result for this benchmark:

https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/goblint-regression/06-symbeq_15-list_entry_nr.c?ref_type=heads

There is a memory leak. Or am I too tired and can't understand the program anymore? :-)

**Comment by fbrausse** [comment]
> I think ESBMC reports the correct result for this benchmark:
> 
> https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/goblint-regression/06-symbeq_15-list_entry_nr.c?ref_type=heads
> 
> There is a memory leak. Or am I too tired and can't understand the program anymore? :-)

As discussed elsewhere, I believe under the SV-COMP valid-memsafety semantics there is no memory leak, because it's still "reachable". For valid-memcleanup it would be a leak.

As we're making lists, I think SV-COMP's verdict for the following valid-memsafety is wrong:
- c/pthread-lit/sssc12-2.yml (our counter-example is valid)
- c/pthread-lit/sssc12_variant-2.yml (our counter-example is valid)
- c/termination-recursive-malloc/chunk1-2.yml (our counter-example is valid; there is malloc but no free; no global variables)

**Comment by lucasccordeiro** [comment]
> As we're making lists, I think SV-COMP's verdict for the following valid-memsafety is wrong:

@fbrausse: can I ask you please to submit a PR to SV-COMP by changing the verdict and also adding the corrected version of the benchmarks?

**Comment by fbrausse** [comment]
After #1295, we now have these wrong ones left in valid-memsafety:
- c/array-examples/relax-2-2.yml
- c/array-memsafety-realloc/array-realloc-2.yml
- ~c/termination-recursive-malloc/chunk1-2.yml~ our cex is valid
- c/loop-industry-pattern/aiob_4.c.v+cfa-reducer.yml
- c/loop-industry-pattern/aiob_4.c.v+lh-reducer.yml
- c/loop-industry-pattern/aiob_4.c.v+lhb-reducer.yml
- c/loop-industry-pattern/aiob_4.c.v+nlh-reducer.yml
- c/pthread/reorder_2-2.yml
- c/pthread/twostage_3-2.yml
- ~c/pthread-lit/sssc12-2.yml~ our cex is valid
- ~c/pthread-lit/sssc12_variant-2.yml~ our cex is valid
- c/ldv-races/race-2_1-container_of.yml
- c/ldv-races/race-2_2-container_of.yml
- c/ldv-races/race-2_3-container_of.yml
- c/ldv-races/race-2_4-container_of.yml
- c/ldv-races/race-2_5-container_of.yml
- c/ldv-races/race-3_1-container_of-global.yml
- c/ldv-races/race-3_2-container_of-global.yml
- c/goblint-regression/04-mutex_46-escape_nr.yml
- c/goblint-regression/09-regions_09-arraylist.yml
- c/goblint-regression/09-regions_11-arraylist_nr.yml
- c/goblint-regression/09-regions_12-arraycollapse_rc.yml
- c/goblint-regression/09-regions_13-arraycollapse_nr.yml
- c/goblint-regression/09-regions_17-arrayloop_nr.yml

**Comment by fbrausse** [comment]
> > 
> 
> @fbrausse: can I ask you please to submit a PR to SV-COMP by changing the verdict and also adding the corrected version of the benchmarks?

Done for these here, see <https://github.com/esbmc/esbmc/issues/1312#issue-1881448695>.

> The memory leak check implemented in ESBMC was disabled in the last competition due to many incorrect results.
> 
> This recent PR reports some numbers: #1250. However, there are still more issues beyond the `getenv` function that needs to be investigated.

We have the memleak check back since #1295. @lucasccordeiro is this issue meant as an umbrella issue for all the remaining benchmarks in memsafety that fail or is there something else you wanted to address here specifically?

**Comment by lucasccordeiro** [comment]
> Done for these here, see https://github.com/esbmc/esbmc/issues/1312#issue-1881448695.

That's great! Thanks very much @fbrausse!

> @lucasccordeiro is this issue meant as an umbrella issue for all the remaining benchmarks in memsafety that fail

Yes, exactly.

**Comment by fbrausse** [comment]
The MR https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/merge_requests/1414 introduced
- c/pthread/reorder_2-2.yml
- c/pthread/twostage_3-2.yml

(from the above list) as copies of fixed benchmarks and has some reasoning as to why they were broken.

**Comment by lucasccordeiro** [comment]
This issue is not valid anymore.
